# Generated by Django 4.1.7 on 2023-05-04 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_vijesti_delete_cringe'),
    ]

    operations = [
        migrations.AddField(
            model_name='vijesti',
            name='objevljen',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vijesti',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vijesti',
            name='test',
            field=models.TextField(),
        ),
    ]
